opt_in_rules:
  - custom_rules
  - unneeded_parentheses_in_closure_argument
  - discouraged_none_name
  - implicit_return
  - let_var_whitespace
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace

large_tuple: 3

line_length: 120

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60

identifier_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
